package id.android.basics.compose.ui.theme

import androidx.compose.ui.graphics.Color

val composerLightPrimary = Color(0xFF825500)
val composerLightOnPrimary = Color(0xFFFFFFFF)
val composerLightPrimaryContainer = Color(0xFFFFDDAE)
val composerLightOnPrimaryContainer = Color(0xFF2A1800)
val composerLightSecondary = Color(0xFF6F5B40)
val composerLightOnSecondary = Color(0xFFFFFFFF)
val composerLightSecondaryContainer = Color(0xFFFADEBC)
val composerLightOnSecondaryContainer = Color(0xFF271904)
val composerLightTertiary = Color(0xFF516440)
val composerLightOnTertiary = Color(0xFFFFFFFF)
val composerLightTertiaryContainer = Color(0xFFD3EABC)
val composerLightOnTertiaryContainer = Color(0xFF102004)
val composerLightError = Color(0xFFBA1B1B)
val composerLightErrorContainer = Color(0xFFFFDAD4)
val composerLightOnError = Color(0xFFFFFFFF)
val composerLightOnErrorContainer = Color(0xFF410001)
val composerLightBackground = Color(0xFFFCFCFC)
val composerLightOnBackground = Color(0xFF1F1B16)
val composerLightSurface = Color(0xFFFCFCFC)
val composerLightOnSurface = Color(0xFF1F1B16)
val composerLightSurfaceVariant = Color(0xFFF0E0CF)
val composerLightOnSurfaceVariant = Color(0xFF4F4539)
val composerLightOutline = Color(0xFF817567)
val composerLightInverseOnSurface = Color(0xFFF9EFE6)
val composerLightInverseSurface = Color(0xFF34302A)
val composerLightPrimaryInverse = Color(0xFFFFB945)

val composerDarkPrimary = Color(0xFFFFB945)
val composerDarkOnPrimary = Color(0xFF452B00)
val composerDarkPrimaryContainer = Color(0xFF624000)
val composerDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val composerDarkSecondary = Color(0xFFDDC3A2)
val composerDarkOnSecondary = Color(0xFF3E2E16)
val composerDarkSecondaryContainer = Color(0xFF56442B)
val composerDarkOnSecondaryContainer = Color(0xFFFADEBC)
val composerDarkTertiary = Color(0xFFB8CEA2)
val composerDarkOnTertiary = Color(0xFF243516)
val composerDarkTertiaryContainer = Color(0xFF3A4C2B)
val composerDarkOnTertiaryContainer = Color(0xFFD3EABC)
val composerDarkError = Color(0xFFFFB4A9)
val composerDarkErrorContainer = Color(0xFF930006)
val composerDarkOnError = Color(0xFF680003)
val composerDarkOnErrorContainer = Color(0xFFFFDAD4)
val composerDarkBackground = Color(0xFF1F1B16)
val composerDarkOnBackground = Color(0xFFEAE1D9)
val composerDarkSurface = Color(0xFF1F1B16)
val composerDarkOnSurface = Color(0xFFEAE1D9)
val composerDarkSurfaceVariant = Color(0xFF4F4539)
val composerDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val composerDarkOutline = Color(0xFF9C8F80)
val composerDarkInverseOnSurface = Color(0xFF1F1B16)
val composerDarkInverseSurface = Color(0xFFEAE1D9)
val composerDarkPrimaryInverse = Color(0xFF825500)